### ISSUE TITLE
python-efl-9999 fails

### ISSUE THREAD

**Issue by rafspiny** [tokiclover/bar-overlay#10]
I have tried to emerge python-efl but it fails, because it cannot resolve the git repo host.
I noticed the repo URI doesn't have the protocol specified, so I add it.
```
EGIT_REPO_URI="git://git.enlightenment.org/bindings/python/${PN}.git"
```

Now I can clone the repo. But it seems to still be failing in the install section.
It cannot find the NEWS file when installing. I removed from mine just to get it work, but I assume that the file can bi simple created.

**Comment by tokiclover** [comment]
Thanks for reporting, fixed.
