### ISSUE TITLE
dev-libs/efl-1.14.0::bar fails with configure: error: pkg-config missing libinput >= 0.6.0

### ISSUE THREAD

**Issue by romildo** [tokiclover/bar-overlay#12]
When emerging `dev-libs/efl-1.14.0::bar` on my `~amd64` system, `configure` fails with the error message:

    configure: error: pkg-config missing libinput >= 0.6.0

**Comment by tokiclover** [comment]
Fixed, thanks for reporting! drm related DEPS were lacking... behind, so cleaned up a few USE flags deps.
