### ISSUE TITLE
media-libs/elementary-1.14.0 fails with fatal error: Elocation.h: No such file or directory

### ISSUE THREAD

**Issue by romildo** [tokiclover/bar-overlay#13]
When emerging `media-libs/elementary-1.14.0` on my ~amd64 system, I am getting the error messages:

    x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I/tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/src/bin -I../..  -I/tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0 -I/tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/src/lib -I../../src/lib -I/tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/src/bin -DPACKAGE_BIN_DIR=\"/usr/bin\" -DPACKAGE_LIB_DIR=\"/usr/lib64\" -DPACKAGE_DATA_DIR=\"/usr/share/elementary\" -D_REENTRANT -I/usr/include/efl-1 -I/usr/include/ecore-sdl-1 -I/usr/include/SDL2 -I/usr/include/efl-1 -I/usr/include/ecore-fb-1 -I/usr/include/efl-1 -I/usr/include/ecore-x-1 -I/usr/include/efl-1 -I/usr/include/ethumb-client-1 -I/usr/include/efl-1 -I/usr/include/ethumb-1 -I/usr/include/efl-1 -I/usr/include/edje-1 -I/usr/include/efl-1 -I/usr/include/ephysics-1 -I/usr/include/bullet -I/usr/include/efl-1 -I/usr/include/embryo-1 -I/usr/include/efl-1 -I/usr/include/ecore-imf-evas-1 -I/usr/include/efl-1 -I/usr/include/ecore-evas-1 -I/usr/include/efl-1 -I/usr/include/ecore-drm-1 -I/usr/include/libdrm -I/usr/include/efl-1 -I/usr/include/ecore-input-evas-1 -I/usr/include/efl-1 -I/usr/include/emotion-1 -I/usr/include/efl-1 -I/usr/include/eeze-1 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/efl-1 -I/usr/include/evas-1 -I/usr/include/fribidi -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/efl-1 -I/usr/include/ector-1 -I/usr/include/luajit-2.0 -I/usr/include/efl-1 -I/usr/include/ecore-imf-1 -I/usr/include/efl-1 -I/usr/include/ecore-input-1 -I/usr/include/efl-1 -I/usr/include/efreet-1 -I/usr/include/efl-1 -I/usr/include/efreet-1 -I/usr/include/efl-1 -I/usr/include/efreet-1 -I/usr/include/efl-1 -I/usr/include/eldbus-1 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/efl-1 -I/usr/include/ecore-file-1 -I/usr/include/efl-1 -I/usr/include/ecore-con-1 -I/usr/include/efl-1 -I/usr/include/eio-1 -I/usr/include/efl-1 -I/usr/include/eet-1 -I/usr/include/efl-1 -I/usr/include/emile-1 -I/usr/include/efl-1 -I/usr/include/ecore-1 -I/usr/include/efl-1 -I/usr/include/eo-1 -I/usr/include/efl-1 -I/usr/include/eina-1 -I/usr/include/eina-1/eina    -O2 -march=native -pipe -Wshadow -Wall -W -Wall -Wextra -Wpointer-arith -Wno-missing-field-initializers -fvisibility=hidden -fdata-sections -ffunction-sections -fpie -c -o elementary_test-test_box.o `test -f 'test_box.c' || echo '/tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/src/bin/'`test_box.c
    In file included from /tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/src/bin/test_actionslider.c:4:0:
    /tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/src/lib/Elementary.h:89:23: fatal error: Elocation.h: No such file or directory
    compilation terminated.
    In file included from /tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/src/bin/test_anim.c:4:0:
    /tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/src/lib/Elementary.h:89:23: fatal error: Elocation.h: No such file or directory
    compilation terminated.
    In file included from /tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/src/bin/test_application_server.c:4:0:
    /tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/src/lib/Elementary.h:89:23: fatal error: Elocation.h: No such file or directory
    compilation terminated.
    Makefile:1010: recipe for target 'elementary_test-test_actionslider.o' failed
    make[3]: *** [elementary_test-test_actionslider.o] Error 1
    make[3]: *** Waiting for unfinished jobs....
    In file included from /tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/src/bin/test_access.c:4:0:
    /tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/src/lib/Elementary.h:89:23: fatal error: Elocation.h: No such file or directory
    In file included from /tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/src/bin/test.c:6:0:
    /tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/src/lib/Elementary.h:89:23: fatal error: Elocation.h: No such file or directory
    compilation terminated.
    compilation terminated.
    Makefile:1024: recipe for target 'elementary_test-test_anim.o' failed
    make[3]: *** [elementary_test-test_anim.o] Error 1
    Makefile:1038: recipe for target 'elementary_test-test_application_server.o' failed
    make[3]: *** [elementary_test-test_application_server.o] Error 1
    Makefile:996: recipe for target 'elementary_test-test_access.o' failed
    make[3]: *** [elementary_test-test_access.o] Error 1
    Makefile:968: recipe for target 'elementary_test-test.o' failed
    make[3]: *** [elementary_test-test.o] Error 1
    In file included from /tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/src/bin/test_box.c:5:0:
    /tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/src/lib/Elementary.h:89:23: fatal error: Elocation.h: No such file or directory
    compilation terminated.
    Makefile:1066: recipe for target 'elementary_test-test_box.o' failed
    make[3]: *** [elementary_test-test_box.o] Error 1
    In file included from /tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/src/bin/test_bg.c:4:0:
    /tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/src/lib/Elementary.h:89:23: fatal error: Elocation.h: No such file or directory
    compilation terminated.
    In file included from /tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/src/bin/test_3d.c:5:0:
    /tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/src/lib/Elementary.h:89:23: fatal error: Elocation.h: No such file or directory
    compilation terminated.
    Makefile:1052: recipe for target 'elementary_test-test_bg.o' failed
    make[3]: *** [elementary_test-test_bg.o] Error 1
    Makefile:982: recipe for target 'elementary_test-test_3d.o' failed
    make[3]: *** [elementary_test-test_3d.o] Error 1
    make[3]: Leaving directory '/tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0-abi_x86_64.amd64/src/bin'
    Makefile:427: recipe for target 'all-recursive' failed
    make[2]: *** [all-recursive] Error 1
    make[2]: Leaving directory '/tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0-abi_x86_64.amd64/src'
    Makefile:621: recipe for target 'all-recursive' failed
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory '/tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0-abi_x86_64.amd64'
    Makefile:504: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by tokiclover** [comment]
Elocation is optional and is disabled by default in the ebuild with
`--disable-elocation` switch in src_configure().
I've checked quickly Elementary.h and found out that Elocation.h is
included if and on if Elocation is enabled...
and the configure script looks fine to me, meaning it won't set
ELM_ELOCATION which would trigger Elocation.h inclusion.

Now, checkout `confdefs.h' in the source directory to see what's happening
there and you could delete manualy the offending line if necessary before
this issue is fixed. (Manual merge with `ebuild $EBUILD configure';
checkout the file; and then `ebuild $EBUILD package' would do the trick.)

I cannot fix it for you because I am running an old EFL/ELM combination, so
merging EFL/ELM-1.14 is not possible.

Or else, post the content of
`/tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/confdefs.h'

and I will see what I can do...

**Comment by romildo** [comment]
There is no `/tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/confdefs.h` file.

    # pwd
    /tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0

    # ls -l
    total 1644
    -rw-r--r-- 1 portage portage  95341 May  6 10:30 ABOUT-NLS
    -rw-r--r-- 1 portage portage  53778 May  6 10:30 aclocal.m4
    -rwxr-xr-x 1 portage portage   5826 Jul 31  2014 ar-lib
    -rw-r--r-- 1 portage portage   6983 May  4 12:17 AUTHORS
    -rw-r--r-- 1 portage portage  53313 Mar 24  2014 ChangeLog
    drwxr-xr-x 2 portage portage     80 May  6 10:32 cmakeconfig
    -rwxr-xr-x 1 portage portage   7333 Dec 16 08:51 compile
    -rw-r--r-- 1 portage portage   3418 Dec 11  2013 COMPLIANCE
    drwxr-xr-x 5 portage portage    160 May  6 10:32 config
    -rwxr-xr-x 1 portage portage  43760 May 21 13:54 config.guess
    -rwxr-xr-x 1 portage portage  18442 Sep  5  2014 config.rpath
    -rwxr-xr-x 1 portage portage  36325 May 21 13:54 config.sub
    -rwxr-xr-x 1 portage portage 780449 May 21 13:54 configure
    -rw-r--r-- 1 portage portage  15453 May  6 10:29 configure.ac
    -rw-r--r-- 1 portage portage  26112 Mar  4  2014 COPYING
    -rw-r--r-- 1 portage portage    230 Dec  8 12:23 COPYING.images
    drwxr-xr-x 7 portage portage    180 May  6 10:32 data
    -rwxr-xr-x 1 portage portage  23566 Jul 31  2014 depcomp
    drwxr-xr-x 4 portage portage    280 May  6 10:32 doc
    -rw-r--r-- 1 portage portage   7012 May  6 10:30 elementary_config.h.in
    -rw-r--r-- 1 portage portage    513 Dec  8 12:23 elementary-cxx.pc.in
    -rw-r--r-- 1 portage portage    490 Dec  8 12:23 elementary.pc.in
    -rw-r--r-- 1 portage portage   2636 May  6 10:30 elementary.spec
    -rw-r--r-- 1 portage portage   2638 Dec 11  2013 elementary.spec.in
    -rw-r--r-- 1 portage portage  15578 Dec 11  2013 INSTALL
    -rwxr-xr-x 1 portage portage  13997 Jul 31  2014 install-sh
    -rw-r--r-- 1 portage portage 283957 May 21 13:54 ltmain.sh
    drwxr-xr-x 2 portage portage    560 May  6 10:32 m4
    -rw-r--r-- 1 portage portage   3882 May  4 12:17 Makefile.am
    -rw-r--r-- 1 portage portage    586 May 16  2014 Makefile_Elm_Helpers.am
    -rw-r--r-- 1 portage portage    461 Dec  8 12:23 Makefile_Eolian_Cxx_Helper.am
    -rw-r--r-- 1 portage portage    703 May 16  2014 Makefile_Eolian_Helper.am
    -rw-r--r-- 1 portage portage  36809 May  6 10:30 Makefile.in
    -rwxr-xr-x 1 portage portage   6873 Jul 31  2014 missing
    -rw-r--r-- 1 portage portage  62760 May  6 10:30 NEWS
    drwxr-xr-x 2 portage portage     60 May  6 10:32 pkgbuild
    drwxr-xr-x 2 portage portage   1400 May  6 10:32 po
    -rw-r--r-- 1 portage portage   3328 May  6 10:30 README
    drwxr-xr-x 9 portage portage    220 May  6 10:32 src
    -rwxr-xr-x 1 portage portage   3977 Jul 31  2014 test-driver
    -rw-r--r-- 1 portage portage    523 Dec 11  2013 TODO

**Comment by tokiclover** [comment]
Sorry to have forgotten the multilib path... same with multilib suffix:
`[...]/work/elementary-1.14.0-abi_x86_64.amd64/confdefs.h'; of course, is
using x86 ARCh replace abi_x86_64.amd64 by the appropriate ABI; and provide
the configure command (to not provide the whole build.log) e.g mine is:

`/var/tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/configure
--prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu
--mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share
--sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking
--disable-silent-rules --libdir=/usr/lib64
--docdir=/usr/share/doc/elementary-1.14.0 --enable-shared --disable-static
--enable-ecore-x --enable-ecore-fb --disable-ecore-sdl
--disable-ecore-wayland --disable-ecore-cocoa --disable-ecore-psl1ght
--disable-ecore-win32 --disable-debug --disable-doc
--disable-build-examples --disable-install-examples --enable-nls
--disable-static --disable-quick-launch --disable-elocation --disable-emap
--disable-eweather --with-tests=none --with-elementary-web-backend=none'

PS: confdefs.h is generated by the configure script.

**Comment by romildo** [comment]
Are you sure there should be a `confdefs.h` file? Again I cannot find one:

    # find /tmp/portage/media-libs/elementary-1.14.0 -iname confdefs.h

No file is found.

Here is the configure call line from the log:

    /tmp/portage/media-libs/elementary-1.14.0/work/elementary-1.14.0/configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --libdir=/usr/lib64 --docdir=/usr/share/doc/elementary-1.14.0 --enable-shared --disable-static --enable-ecore-x --enable-ecore-fb --enable-ecore-sdl --disable-ecore-wayland --disable-ecore-cocoa --disable-ecore-psl1ght --disable-ecore-win32 --disable-debug --disable-doc --disable-build-examples --disable-install-examples --enable-nls --disable-static --disable-quick-launch --disable-elocation --disable-emap --disable-eweather --with-tests=none --with-elementary-web-backend=none

**Comment by tokiclover** [comment]
Sorry for the mis-direction once again... it was from a quick look at the
`configure' script on what is generated to feed different header files.
It appears that it should `elementary_config.h' file instead. The name
could have changed... however, the file is generated
by `config.status' script at the end of configure phase:

[...]
config.status: creating elementary_config.h
[..]

Just checkout the right "config.h" file to pick up... Actually you need
only to checkout `ELM_ELOCATION' definition in that file

$ grep ELOCATION elementary_config.h
/* Elocation support for Elementary
*/
/* #undef HAVE_ELEMENTARY_ELOCATION
*/

Note that this output is for ELM-1.10, so, you should have ELM_ELOCATION
instead; and should be commented out.
Optionally, you could append the part of the resume of the configure phase
that is of interest

[...]
  Features:
    EWeather...............: no
    EMap...................: no
    Web (WebKit)...........: no
    Quick Launch...........: no
    Elocation..............: no
[...]
from the configure output.

**Comment by tokiclover** [comment]
Fixed with 5fd0b29, thanks for reporting.
