### ISSUE TITLE
python-efl wrong links to sources

### ISSUE THREAD

**Issue by SkeLLLa** [tokiclover/bar-overlay#14]
Ebuild for python-efl tries to download sources from:
`https://download.enlightenment.org/rel/bindings/python/python-efl/python-efl-1.14.0.tar.bz2`
but packages are actually located at:
`https://download.enlightenment.org/rel/bindings/python/python-efl-1.14.0.tar.bz2`

**Comment by tokiclover** [comment]
Fixed, thanks for reporting.
