### ISSUE TITLE
REQUIRED_USE: USE flag '+canon_printers_mg5500' is not in IUSE

### ISSUE THREAD

**Issue by joakim-tjernlund** [tokiclover/bar-overlay#19]
Tried to rebuild net-print/cnijfilter-4.00 but got this:
ebuild /var/lib/layman/bar/net-print/cnijfilter/cnijfilter-4.00.ebuild digest
Error(s) in metadata for 'net-print/cnijfilter-4.00':
  REQUIRED_USE: USE flag '+canon_printers_mg5500' is not in IUSE

Seems like later portage(2.2.26) does not like something in this ebuild/class but
I cannot figure out why. Can you?

In make.conf I have: CANON_PRINTERS="mg5500"

**Comment by tokiclover** [comment]
Sorry for the late reply, but... that printer model is not in the list, thus, the error. So, closing because I do not have the time to check that tarball again.

**Comment by joakim-tjernlund** [comment]
hmm, what do you mean with "not in the list"? 
mg5500 is in net-print/cnijfilter-4.00 (but not in net-print/cnijfilter-4.10).
I cannot use net-print/cnijfilter-4.10 as it does not support my printer
