### ISSUE TITLE
 media-sound/hydrogen: Version bump to 0.9.6.1

### ISSUE THREAD

**Issue by dreaming-augustin** [tokiclover/bar-overlay#20]
I was working on the following bug when I found your overlay:

media-sound/hydrogen: Version bump to 0.9.6.1
https://bugs.gentoo.org/show_bug.cgi?id=570814 

I noticed that your version is  hydrogen-0.9.6_rc2.ebuild , which is better than gentoo's   hydrogen-0.9.5, but still lags behind the latest stable release 0.9.6.1.

I'm a complete newbie to gentoo, and it's taking me a while to figure out how to upgrade and install an ebuild. 
I just wanted to let you know.

**Comment by tokiclover** [comment]
Fixed with two commits, thanks for reporting.

**Comment by dreaming-augustin** [comment]
Great!
Just so that you be aware: 
I previously upgraded from 0.9.5 using your previous hydrogen-0.9.6_rc2.ebuild.
The ebuild didn't warn me of important changes since 0.9.5, namely that previously installed drumkits are no longer compatible with the newer versions.   
Indeed, for the last few days, after upgrading, I have been struggling with  
https://github.com/hydrogen-music/hydrogen/issues/348  

Once I have sorted that out, I'll patch the ebuild in the main gentoo tree to include an appropriate, post-upgrade warning.
