### ISSUE TITLE
"configure failed" while emerging mpv-0.20.0

### ISSUE THREAD

**Issue by minami-o** [tokiclover/bar-overlay#24]
Hey there,
I had a systematic "configure failed" while trying to emerge mpv-0.20.0.
The detailed log said that waf (which seems to be [some kind of builder](https://github.com/waf-project/waf)) had no such option as "--enable-gpl3", then listing all the options waf allows.
In the ebuild, line 180 specifies that if the gpl use flag (which is needed for licensing reasons, I think) is enabled, then gpl3 should be enabled in the configure options.
Deleting this manually from the "environment" file allowed me to compile flawlessly.
I spent some time trying to determine what this option, which popped up in the ebuild between 0.18.1 and 0.19.0, belonged to, but could hardly find any clue about it.
All I know is that it is mentioned as required in the mpv changelog for v0.14, but then nothing - don't know why it is present in the 0.19.0 ebuild but not in the previous ones, either.
Cheers

**Comment by tokiclover** [comment]
Fixed, thanks for reporting.
