### ISSUE TITLE
ladish-9999-r2 issues

### ISSUE THREAD

**Issue by simonvanderveldt** [tokiclover/bar-overlay#25]
Hi tokiclover,

First of all thanks for the audio ebuilds!

I just tried to emerge ladish-9999-r2 and ran into some issue:
- [The repo URL is incorrect](https://github.com/tokiclover/bar-overlay/blob/master/media-sound/ladish/ladish-9999-r2.ebuild#L14), should be `https://github.com/LADI/ladish.git`
- The ebuild has [2 patches ](https://github.com/tokiclover/bar-overlay/blob/master/media-sound/ladish/ladish-9999-r2.ebuild#L53) which use `{P}`, but there are no patches with `9999` in the filename.
Also these patches don't seem to be necessary anymore, see https://github.com/LADI/ladish/blob/master/daemon/loader.c#L35 and https://github.com/LADI/ladish/blob/master/wscript#L136 (or this commit https://github.com/LADI/ladish/commit/8e38b76f1d988e2f5bec4508f09779de0801dafe)
- The [arguments passed to `waf`](https://github.com/tokiclover/bar-overlay/blob/master/media-sound/ladish/ladish-9999-r2.ebuild#L75) fail when they are not enabled, `way` responds with `waf: error: no such option: --disable-liblash`. i have no experience with `waf` so I'm not sure if these options should be automatically generated because a matching `--enable-*` option exists or if `waf` only supports explicit options. [There are no `--disable-*` options in ladish's `wscript` file](https://github.com/LADI/ladish/blob/master/wscript#L43).
Since I didn't need lash I've removed them `mywafconfargs`

After fixing these I could emerge ladish-9999-r2.

P.S. I decided to create this issues because I don't know how to correctly fix the waf issue, otherwise I would've made a PR.

**Comment by tokiclover** [comment]
Thanks for reporting, issue fixed by commit  190704c.

**Comment by simonvanderveldt** [comment]
Just pulled in the changes and did a new build, works perfectly fine now :)
Thanks for the quick fix!
