### ISSUE TITLE
missing contact

### ISSUE THREAD

**Issue by jonasstein** [tokiclover/bar-overlay#29]
Hi,
I just wanted to add you to the ticket
https://bugs.gentoo.org/show_bug.cgi?id=598868
but found only
<email>bar@overlay</email>
in the metadata.
If you add your contact to all metadata files, users can send feedback to you and we can assign bugs to you.

**Comment by tokiclover** [comment]
Fixed with 2e0ed21. I don't intend to associate particular authors to particular packages... also I am the only maintainer for now, anyone can do the job or give a hand. So let's use a proper AUTHORS file instead of updating all the metadata files.

**Comment by jonasstein** [comment]
I think this is a misunderstanding. When assigning a bug ticket we need the contact information in the package. It takes lots of time to search for contact information for a single package on external overlays. You could help us a lot by providing the data in metadata.xml https://devmanual.gentoo.org/ebuild-writing/misc-files/metadata/
