### ISSUE TITLE
Issue with cnijfilter-3.60-r2

### ISSUE THREAD

**Issue by DemaroStanberry** [tokiclover/bar-overlay#30]
Running emerge -av net-print/cnijfilter:3/3.60 fails with the following regardless of the model(s) specified:

Failed to emerge net-print/cnijfilter-3.60-r2, Log file:
'/var/tmp/portage/net-print/cnijfilter-3.60-r2/temp/build.log'
Messages for package net-print/cnijfilter-3.60-r2:
> cups debug gtk servicetools canon_printers_ +net +usb **_<-- this is debug output I threw in_**
ERROR: net-print/cnijfilter-3.60-r2::bar failed (prepare phase):
USE Flag 'canon_printers_mg2100' not in IUSE for net-print/cnijfilter-3.60-r2
Call stack:
ebuild.sh, line  115:  Called src_prepare
environment, line 3667:  Called ecnij_src_prepare
environment, line 1295:  Called use 'canon_printers_mg2100'
phase-helpers.sh, line  200:  Called die
The specific snippet of code:
   die "USE Flag '${u}' not in IUSE for ${CATEGORY}/${PF}"

In the ebuild, `inherit ecnij` appears before `PRINTER_MODEL` and `PRINTER_ID` which means the `canon_printers_<MODEL>` USE flags are never defined.

**Comment by tokiclover** [comment]
The only oddball with `CNIJFILTER_{MODEL,ID}` decalred before inheriting the eclass. Fixed with commit 8b3fe4d. Thanks for reporting.
