### ISSUE TITLE
enlightenment-19.3 requires automake-14

### ISSUE THREAD

**Issue by ogelpre** [tokiclover/bar-overlay#7]
[...]
/var/tmp/portage/x11-wm/enlightenment-0.19.3/work/enlightenment-0.19.3/missing: 
line 81: automake-1.14: command not found
WARNING: 'automake-1.14' is missing on your system.
[...]

**Comment by tokiclover** [comment]
Closing... This is a non issue as you just need to update automake to >=v1.14. (Many ebuilds volontarly uses *loose* constraints to no have to contantly updating the overlay.)
